### ISSUE TITLE
promiseIpc.on is not a function

### ISSUE THREAD

**Issue by Dexwell** [sibnerian/electron-promise-ipc#1]
Hey,

This looks like a fantastic package! Running into an issue while getting started though. 

For some reason I get a `TypeError: promiseIpc.on is not a function`. I'm thinking this is due to the way I'm importing the package:

```js 
const promiseIpc = require('electron-promise-ipc');
```

Is this not possible? When I import it as described in the readme like this:

```js 
import promiseIpc from 'electron-promise-ipc';
```

I get a `SyntaxError: Unexpected token import`. I would rather not use a transpiler like Babel.

Thanks in advance.

**Comment by sibnerian** [comment]
Hey y'all,

Sorry I didn't respond to this when it was posted. Somehow, I wasn't watching the repo (even though it was my own), so no notifications popped up. I moved on from Electron, and the issue sat for a long, long time.

I'm sure you've probably moved on to greener pastures by now (or forked the library in @hyperlink's case). However, for anyone who still wants to use this code, I've updated the way I do exports so that the above code should now work. I've added a test for it as well as one for the `import` syntax, and published the whole shebang as version `0.1.0`.

Thanks for filing the issue, and I sincerely apologize for not responding to this for a year!
