### ISSUE TITLE
Support removeListener function

### ISSUE THREAD

**Issue by Szellem** [sibnerian/electron-promise-ipc#5]
It would be nice to have the possibility to unsubscribe specific handlers from the events like in the EventEmitter interface.
https://nodejs.org/api/events.html#events_emitter_removelistener_eventname_listener

**Comment by sibnerian** [comment]
Great suggestion, added in 1.2.0. You can now call `removeListener(route, [listener])` to remove the registered listener.

One interesting difference I found when implementing this is that because this libarary is promise-based, you can't have more than one listener per route. That would be a race condition -- which promise would resolve first and pass data back? So it is different than Node's EventEmitter which can register many listeners.

So the listener param is optional, you can call it with just `removeListener(route)` and it will remove whatever is registered to that route (if anything).
